### ISSUE TITLE
DID Document / Ledger Object metadata

### ISSUE THREAD

**Issue by domwoe** [IDunion/indy-did-resolver#10]
The resolver should be able to not only return the actual DID Document or Ledger Object, but also metadata. 

We need to define what metadata would be useful for a consumer and provide an option to resolve with metadata.

For example, the `did:sov` universal resolver driver  provides the following metadata:

```
Map<String, Object> didDocumentMetadata = new LinkedHashMap<> ();
		didDocumentMetadata.put("network", indyConnection.getPoolConfigName());
		didDocumentMetadata.put("poolVersion", indyConnection.getPoolVersion());
		didDocumentMetadata.put("submitterDid", indyConnection.getSubmitterDid());
		didDocumentMetadata.put("nymResponse", gson.fromJson(jsonGetNymResponse, Map.class));
		didDocumentMetadata.put("attrResponse", gson.fromJson(jsonGetAttrResponse, Map.class));
```
[Source](https://github.com/decentralized-identity/uni-resolver-driver-did-sov/blob/a5871def39516e4f976bd5e8415534bd54d0f9ce/src/main/java/uniresolver/driver/did/sov/DidSovDriver.java#L302)

There's also a section in the DID core spec about recommended properties: https://www.w3.org/TR/did-core/#did-document-metadata

**Comment by paulbastian** [comment]
This should be addressed in the Indy DID Method Spec first.

**Comment by paulbastian** [comment]
We should include metadata from the Indy-VDR `RequestResult` data
