### ISSUE TITLE
Using local Indy Ledger

### ISSUE THREAD

**Issue by vpapanchev** [IDunion/indy-did-resolver#17]
Hello,

Is it possible to configure this driver to resolve DIDs using a local Indy Ledger, e.g., the VON Network?

In my opinion, this is a very useful feature, especially during development stages of projects using the DIF Universal Resolver.

Cheers,
Vasil

**Comment by c2bo** [comment]
This should be doable by configuring the source to a local path with the genesis file of the local von-network. With #12, this would just mean to add -s <path/to/folder> to startup arguments.

**Comment by vpapanchev** [comment]
Thanks for the reply. 
Can I expect #12 to be merged this week?

Additional suggestion: It will be very useful to update README.md of the driver with more detailed instructions on how to configure things like the Indy network or mapped ports :)

**Comment by c2bo** [comment]
Tested with a von-network: 
You need to create a folder e.g. local-network that contains a folder with the name of the network e.g. local which contains a pool_transactions_genesis.json file.

```
networks/
└──local/
     └──pool_transactions_genesis.json
```
You can then start with the option -s <path/to/networks> and resolve via did:indy:local:, e.g.  http://localhost:8080/1.0/identifiers/did:indy:local:<..>

**Comment by vpapanchev** [comment]
I also tested with a local von-network. I ran the indy-resolver both locally and as a docker container as a driver for the Universal Resolver. Everything works as expected.

Thanks very much for the help!
I am closing the issue :)
