### ISSUE TITLE
Driver for universal-resolver does not start

### ISSUE THREAD

**Issue by BernhardFuchs** [IDunion/indy-did-resolver#24]
The driver crashes with following error at startup:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VdrError { kind: PoolNoConsensus, msg: None, source: None }', indy-did-driver/src/main.rs:150:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by c2bo** [comment]
Hey @BernhardFuchs, thanks for reporting the issue.
From what I see, we are not handling pool refresh failures graciously right now and causing a panic if one of the pools can't refresh properly. I will create a fix for the problem in the coming days.

This project is more or less on hold right now and waiting for the indy-vdr merge to create a proper driver with the updates there.

**Comment by c2bo** [comment]
@BernhardFuchs I can hopefully create a small fix + release before my vacation but I deleted the network that was discontinued from the networks repository - so it should work already with a fix coming soonish to properly handle pool refreshs and timeouts. Worst case right now should be that the container restarts a few times if for whatever reason it cannot connect to one of the networks initially.
