### ISSUE TITLE
Driver crashes on startup at the DIF Resolver

### ISSUE THREAD

**Issue by BernhardFuchs** [IDunion/indy-did-resolver#28]
Currently the `indy-did-driver` on the DIF Universal Resolver doesn't start with the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VdrError { kind: PoolNoConsensus, msg: None, source: None }', indy-did-driver/src/main.rs:150:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I can reproduce this issue locally.

**Comment by paulbastian** [comment]
Can you try again?

**Comment by c2bo** [comment]
Everything seems to be working again and we can close this issue, correct @BernhardFuchs?

**Comment by BernhardFuchs** [comment]
Yes, everything is fine again.  
Closing this.
